{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-up.componentFullname" (merge (dict "component" "grafana") .) }}
  labels:
    {{- include "otel-up.componentSelectorLabels" (merge (dict "component" "grafana") .) | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "otel-up.componentSelectorLabels" (merge (dict "component" "grafana") .) | nindent 4 }}
{{- end }}
