{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-up.componentFullname" (merge (dict "component" "tempo") .) }}
  labels:
    {{- include "otel-up.componentSelectorLabels" (merge (dict "component" "tempo") .) | nindent 4 }}
spec:
  type: {{ .Values.tempo.service.type }}
  ports:
    - name: http
      port: {{ .Values.tempo.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: otlp-grpc
      port: {{ .Values.tempo.service.grpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
  selector:
    {{- include "otel-up.componentSelectorLabels" (merge (dict "component" "tempo") .) | nindent 4 }}
{{- end }}
